/* CVS $Id: $ */
package org.hyperdata.proc; 
import com.hp.hpl.jena.rdf.model.*;
 
/**
 * Vocabulary definitions from proc.rdf 
 * @author Auto-generated by schemagen on 21 Mar 2012 14:03 
 */
public class Proc {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static Model m_model = ModelFactory.createDefaultModel();
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://purl.org/stuff/proc/";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    /** <p>components</p> */
    public static final Property components = m_model.createProperty( "http://purl.org/stuff/proc/components" );
    
    /** <p>parameter</p> */
    public static final Property parameter = m_model.createProperty( "http://purl.org/stuff/proc/parameter" );
    
    /** <p>A component of a processing system.</p> */
    public static final Resource Component = m_model.createResource( "http://purl.org/stuff/proc/Component" );
    
    /** <p>An unordered list (set) of components.</p> */
    public static final Resource ComponentList = m_model.createResource( "http://purl.org/stuff/proc/ComponentList" );
    
    /** <p>A processor with differing input and output data types.</p> */
    public static final Resource Converter = m_model.createResource( "http://purl.org/stuff/proc/Converter" );
    
    /** <p>A component which consumes data.</p> */
    public static final Resource DataSink = m_model.createResource( "http://purl.org/stuff/proc/DataSink" );
    
    /** <p>A component which produces data.</p> */
    public static final Resource DataSource = m_model.createResource( "http://purl.org/stuff/proc/DataSource" );
    
    /** <p>A characteristic (named, datatyped value) associated with a component</p> */
    public static final Resource Parameter = m_model.createResource( "http://purl.org/stuff/proc/Parameter" );
    
    /** <p>An ordered list of processors.</p> */
    public static final Resource Pipeline = m_model.createResource( "http://purl.org/stuff/proc/Pipeline" );
    
    /** <p>A component which applies a process to an input to produce an output.</p> */
    public static final Resource Processor = m_model.createResource( "http://purl.org/stuff/proc/Processor" );
    
    /** <p>An ordered set of numeric data.</p> */
    public static final Resource Signal = m_model.createResource( "http://purl.org/stuff/proc/Signal" );
    
    /** <p>A processing system.</p> */
    public static final Resource System = m_model.createResource( "http://purl.org/stuff/proc/System" );
    
}
